---
title: "Most COVID 19 deaths in Europe"
author: "Daniel"
date: "23 6 2020"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
```

## Introduction

This R Markdown presentation shows the countries with the highest number of deaths caused by COVID 19 in Europe.

- The plot shows the 13 countries with the highest number of deaths in Europe
- The data was lastly updated on June 23rd 2020.

## Deaths caused by COVID 19 in Europe (until June 23rd 2020)

```{r plot}
library(plotly)
deaths <- c(42647, 28324, 34657, 8895, 29663, 9696, 5122, 6090, 1534, 1359, 1717, 1523, 690)
countries <- c("United Kingdom", "Spain", "Italy", "Germany", "France", "Belgium", "Sweden", "Netherlands", "Portugal", "Poland", "Ireland", "Romania", "Austria")
df <- data.frame(countries, deaths)

fig <- plot_ly(df, type='bar', x = ~countries, y = ~deaths, text = "Deaths caused by COVID 19 in Europe", name="",
               hovertemplate = paste('%{x}', '<br>Number of Deaths: %{y}<br>'),
               textposition = 'outside')

fig <- fig %>% layout(uniformtext=list(minsize=8, mode='hide'))
fig
```

